Repository gorilla/feeds, pull requests merged in 2023-07, with the labels that each got.

#100 Update go version, add tools for verification and testing
  .circleci/config.yml
  .github/stale.yml
  .github/workflows/issues.yml
  .github/workflows/test.yml
  .gitignore
  AUTHORS
  LICENSE
  Makefile
  README.md
  consume_test.go
  go.mod
  go.sum
Labels: size/L

#101 Added editorconfig
  .editorconfig
Labels: size/S

#102 Update issues.yml
  .github/workflows/issues.yml
Labels: size/XS
